### ISSUE TITLE
question about render image

### ISSUE THREAD

**Issue by PofeiShit** [zju3dv/pvnet-rendering#10]
I had rendered some cat images. So in renders/cat folder there are 0.jpg 0_depth.png 0_RT.pkl ...
And jpg images are normal, but the values of png images are all 0. And the values of png images in LINEMOD/cat/mask is 0 or 1. So I want to ask if the png of rendered images are normal?

**Comment by pengsida** [comment]
Yes. They are used as object masks.

**Comment by PofeiShit** [comment]
but dmap of the render image is all 0, how to used as object masks?

**Comment by pengsida** [comment]
Oh, sorry. I misunderstood your meaning.
Have you visualized the dmap?
```
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

img = Image.open('0_depth.png')
img = np.array(img)
plt.imshow(img)
plt.show()
```

**Comment by PofeiShit** [comment]
Thank you, I used cv2.imread while -1 is ignored
