### ISSUE TITLE
CUDA error at cuCtxCreate: Out of memory

### ISSUE THREAD

**Issue by yunxijun** [zju3dv/pvnet-rendering#13]
I am using GTX1080Ti, only one piece is used for three graphics cards, but why is there insufficient memory? Thank you for your reply
![微信图片_20190726145849](https://user-images.githubusercontent.com/42403620/61932414-f07a5080-afb5-11e9-9909-f210cde66596.png)

**Comment by pengsida** [comment]
Only one piece of what?
It seems impossible for GTX1080Ti to be out of memory for the rendering task.

**Comment by yunxijun** [comment]
Three graphics cards use only one of them, and the other two are available, but still show insufficient memory.

**Comment by yunxijun** [comment]
But execute python run.py --type fuse no problem

**Comment by pengsida** [comment]
Sorry, I don't know.
I rendered images using a GTX1080Ti, but I did not encounter your problem.

**Comment by yunxijun** [comment]
Ok, I am still very grateful for your reply, probably because of the virtual environment I use myself like pvnet.

**Comment by yunxijun** [comment]
This problem is solved here with reference to this, and it is reserved for those who may encounter the same error.[https://blender.stackexchange.com/questions/115915/cuda-error-at-cuctxcreate-out-of-memory-nothing-has-been-changed-since-the-la](url)
