### ISSUE TITLE
Why euler order is set to "szxz"?

### ISSUE THREAD

**Issue by wangg12** [zju3dv/pvnet-rendering#16]
I wonder why the euler order was set to "szxz" [here](https://github.com/zju3dv/pvnet-rendering/blob/master/base_utils.py#L179)? I learned that the default euler order is "sxyz" in blender. Am I missing something? @pengsida

**Comment by pengsida** [comment]
As you know, we use blender to render images.
We adjust the rotation by setting the camera rotation, whose rotation mode is quaternion. I borrowed the rendering code from RenderForCNN, where they converted "szxz" euler to quaternion, so I have to convert the rotation matrix into "szxz" euler.
https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_backend.py#L224
