### ISSUE TITLE
我想请教您三个问题：

### ISSUE THREAD

**Issue by cugwuyanzu** [zju3dv/pvnet-rendering#18]

**Comment by cugwuyanzu** [comment]
第一个是渲染生成的renders文件里每类只有9张，而readme说是生成10000张。
第二个问题是生成的fuse文件里确实是10000张，但是训练pvnet时说没有编号1324的数据，我觉得前两个问题类似，就是生成数据量不对，请问这是怎么回事，或者说我是不是可以在代码里改数量，但是我没找到。
第三个问题是如果我训练好一类，那我想用一个网络接着训练下一类该怎么做，不是给每类训练一个网络。

**Comment by pengsida** [comment]
1. 渲染数量的设置：https://github.com/zju3dv/pvnet-rendering/blob/master/config.py#L42
2. 第二个问题，如果你设置正确，应该没问题。
3. 改变网络的输出通道数，不同通道对应不同类别。

**Comment by cugwuyanzu** [comment]
第一个问题解决了，谢谢您！
第二个问题我换个方式问，就是pvnet训练所用的fuse和renders里面的数据数量都是10000是吗？
第三个问题也就是您已经训练过多类别的网络了是吧，比如您给的预训练模型是可以预测其他类别还是只能预测猫呢？

**Comment by pengsida** [comment]
1. 用的fuse和renders的数量都是10000。但fuse是所有类共用10000张图片，而且不一定所有图片都有每个类。也就是说，cat的fuse图片实际可能不到10000张。
2. 预训练模型只能预测猫。

**Comment by cugwuyanzu** [comment]
你的意思我懂了，但是我训练的时候报的错误感觉就是数据集数量对不上：
FileNotFoundError: [Errno 2] No such file or directory: '/media/cobot/5C8B2D882D247B56/ch/pvnet-master/data/LINEMOD/fuse/1429_mask.png'
我找到问题了，我看了一下生成的fuse文件，正常应该有30000items(pkl,jpg,png三种格式)，但是只有29988items，确实没有1429。

**Comment by cugwuyanzu** [comment]
数据这边的问题解决了，谢谢您！
还有一个问题就是我用自己电脑跑的pvnet，然后报错：RuntimeError: CUDA out of memory. Tried to allocate 163.88 MiB (GPU 0; 7.93 GiB total capacity; 5.60 GiB already allocated; 85.44 MiB free; 1.06 GiB cached)
我尝试用kill杀死进程没用，是我的电脑内存不够，必须要在服务器上跑吗，还是可以改网络代码参数什么的就也能在自己电脑上跑呢？

**Comment by pengsida** [comment]
你把batch size变小就可以了。

**Comment by cugwuyanzu** [comment]
非常感谢！！！
假设我想训练一个可以检测多类别的网络。我是为每一类训练一个模型最后合到一起；还是可以直接一起训练所有的类别呢？
您试过多类别的吗？效果怎么样？

**Comment by pengsida** [comment]
可以直接训练所有的类别。
我试过多类别的，效果还行。

**Comment by cugwuyanzu** [comment]
如果直接训练所有的类别是不是得用更深的主干网络提取特征，然后损失函数也得改呀！
那大概需要改哪些部分的代码呢？

**Comment by pengsida** [comment]
要用更深的网络提取特征。
要改dataset，network和loss。

**Comment by cugwuyanzu** [comment]
我仔细看了一下论文有几个点没懂：
1.公式（6）损失函数里的预测单位向量指的是卷积网络直接输出的还是经过那一系列后续工作（比如投票，计算均值协方差什么的）变换得到的呢
2.x(k)是认为定义的关键点吧，如果是这样，那预测过程计算假设关键点的置信分数就没办法算啦

**Comment by pengsida** [comment]
1. 网络直接输出单位向量。
2. 置信分数按照论文里的算法可以得到。

**Comment by cugwuyanzu** [comment]
也就是说公式2345都属于预测部分呗！那公式2用到了公式1中的xk,我想问xk怎么来的呢？

**Comment by pengsida** [comment]
1. 公式2345不是网络输出的，公式1是网络输出的。
2. 公式2没有x_k。v_k是直接网络输出的。

**Comment by cugwuyanzu** [comment]
您的意思是公式1和2里面的vk是一个东西，都是网络输出的单位向量，我看论文说loss中的vk是真实的单位向量，而v(~)k是网络输出的，那岂不是公式1和2里的vk对应的是loss中的v(~)k啦

**Comment by pengsida** [comment]
训练的时候v_k是真实值，inference的时候v_k是网络输出的。
