### ISSUE TITLE
found bundled python&ImportError: No module named 'transforms3d' &Blender quit

### ISSUE THREAD

**Issue by lilixj** [zju3dv/pvnet-rendering#19]
found bundled python: /home/lxj/blender-2.79b-linux-glibc219-x86_64/2.79/python
Read blend: /home/Storage/lxj/PoseEst/pvnet/pvnet-rendering/data/blank.blend
Traceback (most recent call last):
  File "/home/Storage/lxj/PoseEst/pvnet/pvnet-rendering/blender/render_backend.py", line 7, in <module>
    from transforms3d.euler import euler2mat
ImportError: No module named 'transforms3d'

Blender quit

I install blender-2.79 and configured the path in .config. the code was run in virtual environment and i've installed transforms3d library. Could you help me with this problem?Tks.

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet-rendering/issues/3
