### ISSUE TITLE
您好，我想请教您一个问题

### ISSUE THREAD

**Issue by qmzsuxing** [zju3dv/pvnet-rendering#21]
我用rendering进行渲染的时候，希望根据我指定的位姿将三维模型渲染到背景图片上。但背景图片总会有缩放，无法像fuse中将整张背景图片载入。想请问有什么解决方法呢？

**Comment by pengsida** [comment]
背景图片缩放是我设置的：https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_backend.py#L251
你可以google blender编程。
