### ISSUE TITLE
Some questions regarding the camera pose

### ISSUE THREAD

**Issue by janstuehmer** [zju3dv/pvnet-rendering#22]
Hi!

thank you for the pvnet rendering tool that integrates very well into the LINEMOD data set!

I would like to use pvnet-rendering to generate my own data set for pvnet and have some questions regarding the camera pose:

In render_utils.py:

`

    def get_quat_translation(self, object_to_camera_pose):
        object_to_camera_pose = np.append(object_to_camera_pose, [[0, 0, 0, 1]], axis=0)
        world_to_camera_pose = np.append(self.world_to_camera_pose, [[0, 0, 0, 1]], axis=0)
        object_to_world_pose = np.dot(np.linalg.inv(world_to_camera_pose), object_to_camera_pose)
        quat = mat2quat(object_to_world_pose[:3, :3])
        translation = object_to_world_pose[:3, 3]
        return quat, translation
`

Why is the object pose multiplied with world_to_camera_pose and how did you determine the hard coded parameters in world_to_camera_pose?

Is this the pose that is computed with obj_centened_camera_pos
in render_backend.py?

`

    def render(camera, outfile, pose):
        bpy.context.scene.render.filepath = outfile
        depth_file_output.file_slots[0].path = bpy.context.scene.render.filepath + '_depth.png'

        azimuth, elevation, theta = pose[:3]
        cx, cy, cz = obj_centened_camera_pos(cfg.cam_dist, azimuth, elevation)
        q1 = camPosToQuaternion(cx, cy, cz)
        q2 = camRotQuaternion(cx, cy, cz, theta)
        q = quaternionProduct(q2, q1)
        camera.location[0] = cx  # + np.random.uniform(-cfg.pose_noise,g_camPos_noise)
        camera.location[1] = cy  # + np.random.uniform(-g_camPos_noise,g_camPos_noise)
        camera.location[2] = cz  # + np.random.uniform(-g_camPos_noise,g_camPos_noise)
        camera.rotation_mode = 'QUATERNION'

        camera.rotation_quaternion[0] = q[0]
        camera.rotation_quaternion[1] = q[1]
        camera.rotation_quaternion[2] = q[2]
        camera.rotation_quaternion[3] = q[3]
        # camera.location = [0, 1, 0]
        # camera.rotation_euler = [np.pi / 2, 0, np.pi]

        setup_light(bpy.context.scene)
        rotation_matrix = get_K_P_from_blender(camera)['RT'][:, :3]
        camera.location = -np.dot(rotation_matrix.T, pose[3:])
        bpy.ops.render.render(write_still=True)
    
`

cx, cy, cz seem to be used for the camera rotation only (camera.location is overwritten later with -np.dot(rotation_matrix.T, pose[3:])).

Is there a reason for the particular choice of the parameter cfg.cam_dist = 0.5 instead of 1.0?

Thank you for your advice!

**Comment by pengsida** [comment]
1. I didn't use the `get_quat_translation`.
2. cfg.cms_dist is irrelevant with object pose.
