### ISSUE TITLE
pose format different between render and fuse?

### ISSUE THREAD

**Issue by sherwoac** [zju3dv/pvnet-rendering#28]
Hi.
I'm trying to interpret the pose formats in the {n}_info.pkl files generated by fuse. When I test the blender renderings by projecting the 3d bounding box it works, that doesn't work for the fuse output. The rotation looks roughly right though.

Any assistance very welcome, I hope you can see the attached images.

Thanks.

Adam
![image](https://user-images.githubusercontent.com/11062064/69005661-96ffae00-0925-11ea-9659-641db0451f68.png)
![image](https://user-images.githubusercontent.com/11062064/69005663-9ebf5280-0925-11ea-884c-617ee32e1ef5.png)

**Comment by pengsida** [comment]
We revise the camera intrinsics for this object at https://github.com/zju3dv/pvnet/blob/master/lib/utils/data_utils.py#L321

**Comment by sherwoac** [comment]
Hi. 
Thanks again for being so responsive. I subsequently figured out I could adjust the camera intrinsics according to the offset in the first part of the pkl file, and adjust the focal length by the scaling factor, like this:

            offset_rc = data[0][linemod_cls_names.index(object_name)]
            this_intrinsic_matrix = np.copy(intrinsic_matrix)
            this_intrinsic_matrix[0, 2] += offset_rc[1]
            this_intrinsic_matrix[1, 2] += offset_rc[0]
            this_intrinsic_matrix[0, 0] *= 0.85
            this_intrinsic_matrix[1, 1] *= 0.85

resulting in the bb in the image.

So I'm guessing you keep the camera intrinsic for each object-render instance, so you can back out the pose using pnp with it at the end? Is there any particular reason you decided to do it like this, rather than just update the camera extrinsic for each object-render instance and keep the camera intrinsic constant?

Many thanks.

![image](https://user-images.githubusercontent.com/11062064/69055801-8a9f5200-0a06-11ea-9b72-37501fbfe5af.png)

**Comment by pengsida** [comment]
My partner wrote this code. Maybe he just liked this.
It does not matter with the final pnp, since we did not calculate the object poses for fused images.

**Comment by sherwoac** [comment]
Hi. I solved this using a method I just described in the similar pvnet issue raised

**Comment by JISock** [comment]
Hi, I believe to be more precise it should be

this_intrinsic_matrix[0, 0] = 572.41140
this_intrinsic_matrix[1, 1] = 573.57043

which are intrinsic parameters of the linemod dataset. I guess sherwoac heuristically found 0.85 and it visually works as 700*0.85= 595. 700 comes from the fx, fy used for blender rendering.

Juil
