### ISSUE TITLE
No module named 'transforms3d'

### ISSUE THREAD

**Issue by DC1991** [zju3dv/pvnet-rendering#3]
Dear author,
Can you help me solve this problem? I have installed transforms3d and I can import it from other python files. I do not know why I can't import it in render_backend.py.
The error information is as follows:
found bundled python: /home/xxx/Documents/config/blender-2.79a-linux-glibc219-x86_64/2.79/python
  File "/home/xxx/rendering/blender/render_backend.py", line 7, in <module>
Read blend: /home/xxx/rendering/data/blank.blend
    from transforms3d.euler import euler2mat
ImportError: No module named 'transforms3d'

**Comment by DC1991** [comment]
Solved

**Comment by 571502680** [comment]
How was it solved

**Comment by pengsida** [comment]
blender has its own python.

**Comment by 571502680** [comment]
> blender has its own python.

Thanks，I have solved。

**Comment by caijunhao** [comment]
Hi @571502680, I encounter the same problem and have no idea, could you please tell me how to solve it concretely?

**Comment by caijunhao** [comment]
Can I run the script using standard python instead of blender's one?

**Comment by pengsida** [comment]
No.

**Comment by ming-c** [comment]
A (dumb) workaround is to copy the missing libraries (packages or modules) from the lib dir of your preferred python interpreter to the blender python lib dir (which can be found in the error message).

For instance, for me, the solution is
`cp -r /home/MYNAME/Applications/anaconda3/lib/python3.7/site-packages/transforms3d* /home/MYNAME/Applications/blender-2.79-linux-glibc219-x86_64/2.79/python/lib/python3.5/site-packages/`

Above dirs should be changed according to one's own settings.

**Comment by pengsida** [comment]
A better way is to install pip for blender python and use blender pip to install python libraries.
https://github.com/pengsida/configuration/blob/master/blender/install_pip.py
