### ISSUE TITLE
ValueError: a must be non-empty

### ISSUE THREAD

**Issue by WDKke** [zju3dv/pvnet-rendering#30]
thans for sharing. when I was running run.py this error occurred:

found bundled python: /home/xxx/blender-2.79a-linux-glibc219-x86_64/2.79/python
Read blend: /home/xxx/pvnet-rendering/data/blank.blend

Successfully imported '/home/xxx/pvnet-rendering/data/LINEMOD/cat/cat.ply' in 1.154 sec
Traceback (most recent call last):
  File "/home/xxx/pvnet-rendering/blender/render_backend.py", line 456, in <module>
    batch_render_with_linemod(args, camera)
  File "/home/xxx/pvnet-rendering/blender/render_backend.py", line 366, in batch_render_with_linemod
    bg_imgs = np.random.choice(bg_imgs, size=cfg.NUM_SYN)
  File "mtrand.pyx", line 1083, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:10406)
ValueError: a must be non-empty

Blender quit

would you help me with this?

**Comment by pengsida** [comment]
Have you configured the dataset: https://github.com/zju3dv/pvnet-rendering#create-the-soft-link

**Comment by WDKke** [comment]
Yes I did.
I have run --type fuse successfully, but when I try --type rendering this error occurred.
Thanks for quick replying.

**Comment by pengsida** [comment]
Check that if bg_imgs is empty.

**Comment by WDKke** [comment]
Thank you. It is solved.
The file bg_imgs is indeed empty.

**Comment by kevin860213** [comment]
sorry,i have got the same problem,but i saw the bg_imgs.npy was show up,would you know what happened?
thank you so much

**Comment by MehwishG** [comment]
I am also facing same error. Can you please tell how you have resolved it?
I am attaching the screenshot. Please have a look:
![Capture](https://user-images.githubusercontent.com/53044443/72268287-5c737280-3643-11ea-8ddd-015b5d7b6620.PNG)

**Comment by pengsida** [comment]
Ensure that you have a correct path configuration.
![image](https://user-images.githubusercontent.com/11582122/72305585-34b9f400-36af-11ea-944e-7f5d48ab0a37.png)

**Comment by MehwishG** [comment]
Resolved. Thank You

**Comment by cm107** [comment]
Note that if you executed ```python run.py --type rendering``` before fixing your softlinks, you'll have to delete data/bg_imgs.np, data/blender_poses, and data/dataset_poses before trying again.

**Comment by jinzhiyang1** [comment]
> Note that if you executed `python run.py --type rendering` before fixing your softlinks, you'll have to delete data/bg_imgs.np, data/blender_poses, and data/dataset_poses before trying again.

Hello, I also encountered the same problem, I also created a soft link, but still reported the same error, excuse me, I need to be in render_ backend.py Change in file_ Is the path of bg_imgs?
