### ISSUE TITLE
我想请教一个问题，

### ISSUE THREAD

**Issue by ldd071** [zju3dv/pvnet-rendering#31]
你生成的RT时，为什么好像没有与物体在图像中位置有关系，如果没有关系，你是如何让3D点与图像中2D点形成映射关系

**Comment by pengsida** [comment]
渲染的时候，物体固定在世界坐标系中心，所以RT是相机相对世界坐标系的RT。

**Comment by ldd071** [comment]
那我根据此RT，如何恢复成2D图像像素坐标呢，还有一个问题就是你给的LINEMOD_DRIG文件里的RT是相对于什么的呢

**Comment by pengsida** [comment]
根据透视投影得到2d坐标。
LINEMOD_ORIG里有自己定义的模型，RT相对于它的。
