### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by fransonf** [zju3dv/pvnet-rendering#33]
Hello! We want to train PVNet on a custom dataset containing renderings of the objects of interest. We have .ply files for these objects and wonder if this repo can be used to create pose-annotated training data for PVNet.

If this is the case, what files need to be modified?

**Comment by pengsida** [comment]
It probably works by revising the `ply_path` and `output_dir` in this function  https://github.com/zju3dv/clean-pvnet/blob/master/lib/datasets/tless/handle_rendering_data.py#L50

**Comment by fransonf** [comment]
I thought rendering custom datasets was done in this repo, not in clean-pvnet. Is this repo only for generating LINEMOD datasets?

**Comment by pengsida** [comment]
This repo contains many hard coding.
If you want to use this repo, you might need to revise many places.

**Comment by fransonf** [comment]
Thanks

**Comment by RiplleYang** [comment]
> Thanks



> I thought rendering custom datasets was done in this repo, not in clean-pvnet. Is this repo only for generating LINEMOD datasets?

Sorry to bother you. Did you succeed in the end? If possible, thank you very much for your help
