### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by ghost** [zju3dv/pvnet-rendering#34]
Hi,
The link to download LINEMOD seems to be dead, and the LINEMOD dataset downloaded from the clean-pvnet repository lacks a file "rot4.rot" in $class_type/data.
Could you update the link or precise what this file is ?

**Comment by pengsida** [comment]
I have updated the link.
Which object lacks "rot4.rot"?

**Comment by ghost** [comment]
Thank you for your reactivity.
Each one lacks it in the LINEMOD dataset downloaded at the beginning of the week from https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/EXK2K0B-QrNPi8MYLDFHdB8BQm9cWTxRGV9dQgauczkVYQ?e=beftUz
This was the link given in section "Installation" of clean-pvnet/README.md

**Comment by pengsida** [comment]
Which dataset, Linemod or Linemod_orig?
The Linemod_orig in my computer has `rot4.rot` for every objects.

**Comment by ghost** [comment]
It is in Linemod, which I downloaded from the link I found in clean-pvnet/README.md. I see that its formatted for the project, and maybe that's why `rot4.rot` is absent. I'll check in the link you just updated and come back to you.

**Comment by pengsida** [comment]
Linemod does not have `rot*.rot`.
You might mix up Linemod and Linemod_orig.
