### ISSUE TITLE
关于渲染的几个问题请教

### ISSUE THREAD

**Issue by g185211** [zju3dv/pvnet-rendering#35]
1. 有关渲染的代码中“num_samples = cfg.NUM_SYN=10，”ratio = (begin_elevation + 90) / 180
        num_points = int(num_samples // (1 - ratio))“，num_samples和num_points有啥关系？
2.采样完pose后用blender去渲染，对应的程序段在哪里？
多谢，希望的到您的指点！

**Comment by pengsida** [comment]
1. num_samples是渲染图片的数量。
2. num_points是球面viewpoints的总数量。

**Comment by jinzhiyang1** [comment]
1
