### ISSUE TITLE
blender permission denied

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/pvnet-rendering#37]
您好，我想请问您遇到过这种情况吗？是因为blender下载错误了吗
root@terminal35f8111b:/opt/data/private/zhuyazhi/pvnet-rendering-master# python run.py --type rendering
sh: 1: /opt/data/private/zhuyazhi/blender-2.79a-linux-glibc219-x86_64/blender: Permission denied

**Comment by pengsida** [comment]
没有执行blender命令的权限。

**Comment by zhuyazhi** [comment]
ok,这个problem应该解决了~
