### ISSUE TITLE
SUN2012 or SUN397? 

### ISSUE THREAD

**Issue by joefriel** [zju3dv/pvnet-rendering#4]
The README mentions both SUN2012 and SUN397:

Download the SUN397
```
wget http://groups.csail.mit.edu/vision/SUN/releases/SUN2012.tar.gz
```

I downloaded SUN2012, but it does not appear to have the correct format.  From render_utils.py:
`
        img_paths = glob.glob(os.path.join(cfg.SUN, 'JPEGImages/*'))
`

I don't see 'JPEGImages' in SUN2012.

**Comment by joefriel** [comment]
Looks like the proper dataset is SUN2012 in PASCAL format:

http://groups.csail.mit.edu/vision/SUN/releases/SUN2012pascalformat.tar.gz

**Comment by pengsida** [comment]
Thank for your correcting.

**Comment by pengsida** [comment]
It is SUN2012 that we use for background images, while we call its paper SUN397.
