### ISSUE TITLE
Blender quit（ValueError: a must be non-empty）

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/pvnet-rendering#40]
您好，请问以下的错误是什么原因呀
root@terminal35f8111b:/opt/data/private/zhuyazhi/pvnet-rendering-master# python run.py --type rendering
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
found bundled python: /root/blender-2.79a-linux-glibc219-x86_64/2.79/python
Read blend: /opt/data/private/zhuyazhi/pvnet-rendering-master/data/blank.blend

Successfully imported '/opt/data/private/zhuyazhi/pvnet-rendering-master/data/LINEMOD/ape/ape.ply' in 1.891 sec
Traceback (most recent call last):
  File "/opt/data/private/zhuyazhi/pvnet-rendering-master/blender/render_backend.py", line 456, in <module>
    batch_render_with_linemod(args, camera)
  File "/opt/data/private/zhuyazhi/pvnet-rendering-master/blender/render_backend.py", line 366, in batch_render_with_linemod
    bg_imgs = np.random.choice(bg_imgs, size=cfg.NUM_SYN)
  File "mtrand.pyx", line 1083, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:10406)
ValueError: a must be non-empty

Blender quit

**Comment by zhuyazhi** [comment]
ln -s /opt/data/private/zhuyazhi/pvnet-rendering-master/data/LINEMOD LINEMOD
ln -s /opt/data/private/zhuyazhi/pvnet-rendering-master/data/LINEMOD_ORIG LINEMOD_ORIG
ln -s /opt/data/private/zhuyazhi/pvnet-rendering-master/data/SUN2012pascalformat SUN
我这样建立link的，是不是需要加./data

**Comment by pengsida** [comment]
在data目录下建立软链接。

**Comment by zhuyazhi** [comment]
重新建立连接之后还是出现以上问题：
ln -s /opt/data/private/zhuyazhi/pvnet-rendering-master/data/datasets/LINEMOD ./data/LINEMOD
ln -s /opt/data/private/zhuyazhi/pvnet-rendering-master/data/datasets/LINEMOD_ORIG ./data/LINEMOD_ORIG
ln -s /opt/data/private/zhuyazhi/pvnet-rendering-master/data/datasets/SUN2012pascalformat ./data/SUN
![image](https://user-images.githubusercontent.com/48109799/81657094-2f589480-946a-11ea-8505-012ca0820ba4.png)

**Comment by zhuyazhi** [comment]
bg_images.npy is empty

**Comment by pengsida** [comment]
你可以打断点看看

**Comment by zhuyazhi** [comment]
谢谢您~这个问题我解决了，默认合成10张图片，然后我改成了10000，render过程正常，但是后面的depth图片是EXR的格式（10_depth.png0001.exr），我看代码里面有一个exr_to_png（）函数，是需要10000张图片渲染完毕才会调用这个函数将exr->png吗~
![image](https://user-images.githubusercontent.com/48109799/81886824-43b6a180-95d0-11ea-8694-263ba12590e3.png)

**Comment by zhuyazhi** [comment]
谢谢您！这个问题我解决了，默认合成10张图片，然后我改成了10000，render过程正常，但是后面的depth图片是EXR的格式（10_depth.png0001.exr），我看代码里面有一个exr_to_png（）函数，是需要10000张图片渲染完毕才会调用这个函数将exr->png吗
![image](https://user-images.githubusercontent.com/48109799/81886898-76f93080-95d0-11ea-966e-96b3a8bf4d07.png)

**Comment by pengsida** [comment]
对的。

**Comment by jinzhiyang1** [comment]
您好 请问您运行完这个代码了么？我在跑这个数据集的时候，遇到一些问题，方便为我解答一下么？

**Comment by jinzhiyang1** [comment]
> 谢谢您！这个问题我解决了，默认合成10张图片，然后我改成了10000，render过程正常，但是后面的depth图片是EXR的格式（10_depth.png0001.exr），我看代码里面有一个exr_to_png（）函数，是需要10000张图片渲染完毕才会调用这个函数将exr->png吗
> ![image](https://user-images.githubusercontent.com/48109799/81886898-76f93080-95d0-11ea-966e-96b3a8bf4d07.png)

我也遇到了同样的问题，建立软连接之后仍然报了同样的错误，请问您是怎么解决的，方便为我解答一下么？谢谢！

**Comment by lyj9494** [comment]
我也遇到了一样的情况，请问应该怎么解决呀，谢谢
![image](https://user-images.githubusercontent.com/91005527/161981486-da3a73fe-281f-44bc-aed2-6f04d13fbd29.png)
