### ISSUE TITLE
training data for clean-pvnet

### ISSUE THREAD

**Issue by darwinharianto** [zju3dv/pvnet-rendering#44]
Hello, thanks for the sharing great tools!

Currently I am trying to make this works on blender 2.82.
I have a few question on structuring the dataset.
Based on https://github.com/zju3dv/clean-pvnet#training-on-the-custom-object, I would need some information like camera position, diameter, poses, etc.

`./data/blender_poses` would be pose data. This data should be split by array and saved as .npy files

camera.txt would be linemod from
```
intrinsic_matrix = {
        'linemod': np.array([[572.4114, 0., 325.2611],
                              [0., 573.57043, 242.04899],
                              [0., 0., 1.]]),
        'blender': np.array([[700.,    0.,  320.],
                             [0.,  700.,  240.],
                             [0.,    0.,    1.]])
    }
```

For the mask images, how can I generate them?
should I read them from exr files, then make my own mask?

**Comment by pengsida** [comment]
You could read mask from the rendered depth.

**Comment by darwinharianto** [comment]
Thanks, using this method works.
https://github.com/zju3dv/clean-pvnet/blob/f54fefa1e88cc50cce603f37815a011f3137d137/lib/utils/pvnet/pvnet_data_utils.py#L57

I just need to multiply by 255 to get the black white images.

I am sorry, but I just realized generated pose data seems to be different than what I expected.
for the generated pose, `./data/dataset_poses/cat_poses.npy`, this seems to be having N * 6 `N means number of images, 6 is the value in array.`
for the pose at clean-pvnet, it seems to be a dcm. How can I convert this N*6 to DCM?

**Comment by darwinharianto** [comment]
It seems like I can read DCM from _RT pkl files.
I just need to take RT for pose, and K for camera.txt.

Is this right?

**Comment by pengsida** [comment]
Yes.
