### ISSUE TITLE
Question about azimuths and elevations

### ISSUE THREAD

**Issue by pyni** [zju3dv/pvnet-rendering#45]
Hi, thanks to share your code.
I am not clear about the following parts:
        azimuths, elevations = self.sample_sphere(num_samples)
        euler_sampler = stats.gaussian_kde(eulers.T) 
        eulers = euler_sampler.resample(num_samples).T
        eulers[:, 0] = azimuths
        eulers[:, 1] = elevations
So what the meaning of the last two steps?  I know these eulers are 'szxz'. 
I am also not clear about the meaning of eulers[:, 2]. Why it requires no changes?

Thanks!

**Comment by pengsida** [comment]
The third part is tilt.
