### ISSUE TITLE
关于自由调整渲染模型在图片中的位置

### ISSUE THREAD

**Issue by yyzzyy78** [zju3dv/pvnet-rendering#46]
十分感谢作者的分享！
我想在渲染时将目标物体固定在渲染图片的中心位置，或自由调整目标物体出现在图片中的位置。
我尝试修改了render_backend.py render类中的camera.location 但没有成功。
我认为obj模型是固定在世界坐标系原点的，我该如何调整相机，使其对准模型的中心？

**Comment by yyzzyy78** [comment]
抱歉，以解决，在obj_centened_camera_pos()中可以修改。

**Comment by DCC-lzhy** [comment]
你好，请问可以设置目标的转动角度范围吗，合成的图像是各个角度，背面的图对训练有难度啊。我在congfig文件虽然有看到一些参数的最大最小值，但我在代码里搜索该参数没找到，作者设置的这些参数没有用到好像。

**Comment by DCC-lzhy** [comment]
我看到角度的采样是在sample_sphere，但这段代码我不知道咋改，才能限定在一定的范围里

**Comment by pengsida** [comment]
你需要看懂这段代码。

**Comment by DCC-lzhy** [comment]
嗯，已经看懂了，改成我需要的样子了
