### ISSUE TITLE
render my own data

### ISSUE THREAD

**Issue by gaoyuchris** [zju3dv/pvnet-rendering#47]
I want to render the pascal3d like dataset, and find that your code may include pascal 3d, how can I use it.  And I am a newcomer in this fields, it's difficult for me to understand the whole render process and your code, du u have any suggestion? thank u very much!

**Comment by pengsida** [comment]
1. My code cannot render the models in pascal3d.
2. You could learn about blender python api.

**Comment by gaoyuchris** [comment]
> 1. My code cannot render the models in pascal3d.
> 2. You could learn about blender python api.

Thank you for your reply. Moreover, I am confuse that why we set the azimuths and elevations sampled around a sphere, while the title and trans from the original pose? why not directly use the original object pose?

**Comment by pengsida** [comment]
Sorry, I read this message, but I forgot to reply it.
I follow previous methods that sample poses on the sphere.
The poses in the training data does not cover all the angles.
