### ISSUE TITLE
How to get the rendered depth?

### ISSUE THREAD

**Issue by wangg12** [zju3dv/pvnet-rendering#5]
Hi, I am not familiar with blender. 

When I used the code for rendering , I noticed that you convert the rendered depth map to binary masks (see [https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_utils.py#L218](https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_utils.py#L218)).
 
In addition, I found that the values in depth map are not equal to the depth map rendered by an OpenGL renderer.

Could you give me some hints on this? How can I get the same depth map results to that of an OpenGL renderer?

**Comment by pengsida** [comment]
1. The depth map rendered by OpenGL is correct.
2. The dmap here https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_utils.py#L217 is normalized to 0-1 by blender https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_backend.py#L115
3. The dmap generated by blender is from camera to object, not to image plane. You need manually compute the depth value.

**Comment by wangg12** [comment]
Thanks for your explanation. Another question, in your code, the blender K is obtained from 
```
camera = bpy.data.objects['Camera']
```
 and 
```
K = [[700., 0., 320.], [0., 700., 240.], [0., 0., 1.]]
``` 
Why fx=fy=700? Is this a default blender camera? 

Is it possible to apply a custom camera intrinsic, e.g. using the camera intrinsic in LINEMOD?

**Comment by pengsida** [comment]
1. The camera intrinsic matrix changes with image size, which is 640 x 480 in this setting.
2. I had attempted to customize the intrinsic matrix but failed. I believe there is a way to modify the camera matrix, as described at here https://kun-liu.com/blog/graphics/2012/03/17/simulate-real-cameras-in-blender.html

**Comment by wangg12** [comment]
Now I can adjust the camera intrinsic by tuning `lens, shift_x, shift_y`, but I can not make `K[0,0]` and `K[1,1]` to be different. Any ideas?

**Comment by pengsida** [comment]
I also faced the same situation, and finally I gave up.

**Comment by chenynCV** [comment]
So, how do you get the depth as camera model finally?

**Comment by pengsida** [comment]
What do you mean by "get the depth as camera model"?

**Comment by chenynCV** [comment]
‘The dmap generated by blender is from camera to object, not to image plane. You need manually compute the depth value.’
So, do I still need to due with this issue?

**Comment by pengsida** [comment]
Yes.
```
dmap, _, _ = [read_exr(s, width, height) for s in exr_image.channels('BGR', Imath.PixelType(Imath.PixelType.FLOAT))]
row_col = np.argwhere(dmap != 1)
xy = row_col[:, [1, 0]].astype(np.float32)  # flip xy
D = dmap[dmap != 1]
K_P = read_pickle(pose_path)
K = K_P['K']
L = np.sqrt(np.power(xy[:, 0] - K[0, 2] + 0.5, 2) + np.power(xy[:, 1] - K[1, 2] + 0.5, 2) + np.power(K[0, 0], 2))
d = D / L * K[0, 0]
dmap[row_col[:, 0], row_col[:, 1]] = d
```

**Comment by chenerg** [comment]
I'm confused with the calculated depth from code above, the result is also between 0 and 1 and the calculated dmap is also near the orginal dmap.

**Comment by pengsida** [comment]
It is normal for the calculated dmap to be near the original dmap.

**Comment by Liuchongpei** [comment]
> Yes.
> 
> ```
> dmap, _, _ = [read_exr(s, width, height) for s in exr_image.channels('BGR', Imath.PixelType(Imath.PixelType.FLOAT))]
> row_col = np.argwhere(dmap != 1)
> xy = row_col[:, [1, 0]].astype(np.float32)  # flip xy
> D = dmap[dmap != 1]
> K_P = read_pickle(pose_path)
> K = K_P['K']
> L = np.sqrt(np.power(xy[:, 0] - K[0, 2] + 0.5, 2) + np.power(xy[:, 1] - K[1, 2] + 0.5, 2) + np.power(K[0, 0], 2))
> d = D / L * K[0, 0]
> dmap[row_col[:, 0], row_col[:, 1]] = d
> ```


Hi! if I undestood correctly, 'dmap' should be the distances for origion of camera to points on surface of object. And the depth values are calcuated by similarity ratio. As shown in pictrue, we can know the 'z' value of translation is around 1.0. But the depth values 'd'  are around 0.5 which should be near 'z' value.
![2345截图20210823165718](https://user-images.githubusercontent.com/34116796/130423356-0e85e70d-a2bc-42e6-9edc-1d2d925fc863.jpg)

![2345截图20210823165748](https://user-images.githubusercontent.com/34116796/130423361-dcd21c3b-7c7f-49f2-8522-469e5d611911.jpg)
May I ask what went wrong?
@wangg12 How do you deal with it in [GDR-Net](https://github.com/THU-DA-6D-Pose-Group/GDR-Net)?

**Comment by Liuchongpei** [comment]
The problem is solved.
I found that the max depth is limited to 2.
https://github.com/zju3dv/pvnet-rendering/blob/7c36dfa5575dbb587fe766a88bb5dd1e517d725c/config.py#L53

> Yes.
> 
> ```
> dmap, _, _ = [read_exr(s, width, height) for s in exr_image.channels('BGR', Imath.PixelType(Imath.PixelType.FLOAT))]
> row_col = np.argwhere(dmap != 1)
> xy = row_col[:, [1, 0]].astype(np.float32)  # flip xy
> D = dmap[dmap != 1]
> K_P = read_pickle(pose_path)
> K = K_P['K']
> L = np.sqrt(np.power(xy[:, 0] - K[0, 2] + 0.5, 2) + np.power(xy[:, 1] - K[1, 2] + 0.5, 2) + np.power(K[0, 0], 2))
> d = D / L * K[0, 0]
> dmap[row_col[:, 0], row_col[:, 1]] = d
> ```
To get the actual depth values, 'dmap' in the last row should be multiplied by 2.
