### ISSUE TITLE
关于blender：error；无法识别参数

### ISSUE THREAD

**Issue by jinzhiyang1** [zju3dv/pvnet-rendering#51]
作者您好；
         十分感谢作者的分享，我在运行的时候碰到关于blender的问题
![blender报错](https://user-images.githubusercontent.com/73972318/98183202-a4e97d00-1f42-11eb-9a99-933e09625d08.png)向请问作者该怎么解决。

**Comment by pengsida** [comment]
Use `blender-2.79a`.

**Comment by jinzhiyang1** [comment]
> Use `blender-2.79a`.

谢谢，但是我换成2.79a，还是报了同样的错误。

**Comment by pengsida** [comment]
截图看看。

**Comment by jinzhiyang1** [comment]
报了两个错误，一个是关于blender无法识别参数，另一个应该是关于内存的，但我觉得我的内存是足够的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/pvnet-rendering"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午2:32
收件人:&nbsp;"zju3dv/pvnet-rendering"<pvnet-rendering@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<1831099341@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/pvnet-rendering] 关于blender：error；无法识别参数 (#51)





 
截图看看。

**Comment by pengsida** [comment]
我不清楚具体问题，你自己debug看看吧。

**Comment by jinzhiyang1** [comment]
您方便把blender rendering运行之后的数据集发给我看一下么？我只跑出来了10000张fuse的那个数据集。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/pvnet-rendering"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午3:13
收件人:&nbsp;"zju3dv/pvnet-rendering"<pvnet-rendering@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<1831099341@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/pvnet-rendering] 关于blender：error；无法识别参数 (#51)





 
我不清楚具体问题，你自己debug看看吧。

**Comment by pengsida** [comment]
那个数据集很大，不好上传。
