### ISSUE TITLE
bpy.data  is none

### ISSUE THREAD

**Issue by jinzhiyang1** [zju3dv/pvnet-rendering#52]
我在运行‘render_backend.py’时报错，然后我打印‘bpy.data’，显示为None。请问这应该怎么处理呢？/home/jzy/图片/bpy.data.png

**Comment by jinzhiyang1** [comment]
![Uploading bpy.data.png…]()

**Comment by pengsida** [comment]
我看不到你传的图片。

**Comment by jinzhiyang1** [comment]
您好 感谢你的回复，我现在把图片发给您。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/pvnet-rendering"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上10:31
收件人:&nbsp;"zju3dv/pvnet-rendering"<pvnet-rendering@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<1831099341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/pvnet-rendering] bpy.data  is none (#52)





 
我看不到你传的图片。

**Comment by jinzhiyang1** [comment]
会不会是bpy库里面少了文件，我找到bpy库发现里面没有data这个文件。请问我该怎么安装bpy库呢？我用的是ubuntu18.04




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/pvnet-rendering"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 晚上10:31
收件人:&nbsp;"zju3dv/pvnet-rendering"<pvnet-rendering@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<1831099341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/pvnet-rendering] bpy.data  is none (#52)





 
我看不到你传的图片。

**Comment by pengsida** [comment]
bpy库是blender自带的。

**Comment by jinzhiyang1** [comment]
感谢您的耐心解答，代码中调用了bpy.data.objects,但是在bpy库中并没有data的文件夹。当我运行render_backend.py时报错，这是为什么呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/pvnet-rendering"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午4:29
收件人:&nbsp;"zju3dv/pvnet-rendering"<pvnet-rendering@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<1831099341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/pvnet-rendering] bpy.data  is none (#52)





 
bpy库是blender自带的。

**Comment by pengsida** [comment]
报什么错

**Comment by jinzhiyang1** [comment]
bpy.data 是NoneType


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/pvnet-rendering"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 下午5:30
收件人:&nbsp;"zju3dv/pvnet-rendering"<pvnet-rendering@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<1831099341@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/pvnet-rendering] bpy.data  is none (#52)





 
报什么错

**Comment by pengsida** [comment]
无法直接运行`render_backend.py`，需要通过blender运行。

**Comment by jinzhiyang1** [comment]
> 无法直接运行`render_backend.py`，需要通过blender运行。
好的  感谢您的耐心解答。
