### ISSUE TITLE
AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'

### ISSUE THREAD

**Issue by Xiaflowers** [zju3dv/pvnet-rendering#53]
你好，我在运行时出现下面这个问题：AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'具体内容是：
Traceback (most recent call last):
  File "/home/lee/py/pvnet-rendering/blender/render_backend.py", line 453, in <module>
    camera, depth_file_output = setup()
  File "/home/lee/py/pvnet-rendering/blender/render_backend.py", line 93, in setup
    bpy.context.scene.render.alpha_mode = 'TRANSPARENT'
AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'
请问这该如何解决呢？

**Comment by pengsida** [comment]
你用什么版本的blender

**Comment by Xiaflowers** [comment]
2.83

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/103153255-40bc9a00-47ca-11eb-83ec-1e415bf50c6e.png)

**Comment by YuQiao0303** [comment]
你好，我用这个方法成功了（虽然我用的不是这个脚本，但解决了同款报错）。Hi, I've just tried the following method and it worked.

: https://blenderartists.org/t/2-80-cheat-sheet-for-updating-add-ons/1148974.

这个链接里面说： It's said in it that:

`So I just ran into this problem updating Level Builder, and the answer didn’t come up in a Google search so I am updating this necro thread. 

bpy.data.scenes[“Scene”].render.alpha_mode : [“SKY”, “TRANSPARENT”] is now 

bpy.data.scenes[“Scene”].render.film_transparent : [0, 1] Here’s hoping Google finds this answer for the next coder.`

So I modified my code like this and it worked fine:

    if g_background_image_path == 'TRANSPARENT':
      # bpy.context.scene.render.alpha_mode = g_background_image_path # 2.79
      bpy.context.scene.render.image_settings.color_mode = 'RGBA' # blender 2.8
      bpy.context.scene.render.film_transparent = 1 # 0 for "SKY"; 1 for "TRANSPARENT

由于blender2.7和2.8之间还有很大的改动，不排除还会有其他不兼容的地方
