### ISSUE TITLE
Question about the code which uses to get the R&t

### ISSUE THREAD

**Issue by ziyedy** [zju3dv/pvnet-rendering#55]
Thank you for sharing your work. I'd like to use blender to render my dataset too.  But I'm not familiar with blender.
When I use the function "get_3x4_RT_matrix_from_blender()" to get the groundtruth R&t and reprojection according to the generated R&t, it meets some problem like below
![error](https://user-images.githubusercontent.com/39487834/103530847-2453e800-4ec3-11eb-96c3-74198394faba.png)

I think the reprojection code is ok because I have already tested in the LINEMOD dataset, so do you know what wrong with that? looking forward to your reply

**Comment by pengsida** [comment]
How did you generate the image?
