### ISSUE TITLE
fix the background as one image

### ISSUE THREAD

**Issue by zhuyazhi** [zju3dv/pvnet-rendering#56]
您好，请问代码里面哪一部分可以控制不要crop背景图片，我改了很多参数都不能固定一张背景图片不变；
会产生螺旋状&crop的背景图。
<img width="432" alt="截屏2021-01-05 下午3 43 08" src="https://user-images.githubusercontent.com/48109799/103619442-b82dbe80-4f6c-11eb-8dca-fe67f7638caf.png">

期待您回复～

**Comment by pengsida** [comment]
可以用mask把背景图片替换掉。
