### ISSUE TITLE
转换数据集格式

### ISSUE THREAD

**Issue by Xiaflowers** [zju3dv/pvnet-rendering#57]
您好！感谢你的分享，我想问一下如何将render数据集转换成Linemod格式呢？因为我想用您的clean-pvnet训练rendering出来的数据，期待您的回复！

**Comment by pengsida** [comment]
![image](https://user-images.githubusercontent.com/11582122/104096302-ad5d8b80-52d6-11eb-9960-8a0fbfe8b131.png)
