### ISSUE TITLE
What is the role of b_empty?

### ISSUE THREAD

**Issue by wangg12** [zju3dv/pvnet-rendering#6]
Hi, I wonder what is the effect of `b_empty = parent_obj_to_camera(camera)` here [https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_backend.py#L100](https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_backend.py#L100).

It is created but not used, does it have any special effect?

**Comment by pengsida** [comment]
Originally I set a parent of camera in (0, 0, 0), wishing camera always points to the object.
Then I found a new method (quaternion) to place camera and removed the codes related to the parent object.

**Comment by wangg12** [comment]
So `b_empty` is useless now? What about the effect of `cfg.cam_dist` in placing the camera? I found that the rendered result has little visual difference when I set it to `0.5` and `10`. Does it affect the translation and how does it affect the pose?

**Comment by pengsida** [comment]
`b_empty` is useless.
`cfg.cam_dist` is useless too.
I place the camera according to the parameter `pose` in https://github.com/zju3dv/pvnet-rendering/blob/master/blender/render_backend.py#L220
`cfg.cam_dist` could be regarded as a placeholder to adjust the rotation of camera.
I modify the translation of camera using `pose[3:]`
