### ISSUE TITLE
About blender 2.79a

### ISSUE THREAD

**Issue by Kewenjing1020** [zju3dv/pvnet-rendering#60]
Hi, 

I'm trying to use this repo to generate rendering and fused LINEMOD dataset. I'm quite curious about 'Download blender 2.79a'. Could you kindly give some instructions on where to download it and how to install it? 

Thank you very much!

**Comment by pengsida** [comment]
https://download.blender.org/release/Blender2.79/

**Comment by mmkolbe** [comment]
What worked for me was the following. I was in PVNet environment using Python 3.7.

`wget https://download.blender.org/release/Blender2.79/blender-2.79a-linux-glibc219-x86_64.tar.bz2`
tar -xjf blender-2.79a-linux-glibc219-x86_64.tar.bz
sudo mv blender-2.79a-linux-glibc219-x86_64 /opt/blender-2.79a
sudo ln -s /opt/blender-2.79a/blender /usr/local/bin/blender
blender

Down the road, when I need to run the python run.py --type rendering, a Python installation bundled (Python 3.5) with Blender will be found and considered. So I needed to install some packages from there. At least transformers3d==0.3.1 and easydict.
