### ISSUE TITLE
更改渲染图片的输出大小后，出现pose对不齐的现象

### ISSUE THREAD

**Issue by lqz123** [zju3dv/pvnet-rendering#61]
首先非常感谢作者的工作。
我想用这个代码渲染其他的模型来生成数据集，对代码做出了一点修改后得到的很好的结果。
![Figure_640_480](https://user-images.githubusercontent.com/43459433/116983312-82230000-acfc-11eb-8b9d-f6c334a0c55f.png)

但是由于我需要的是400*400的图片大小，所以我更改了输出图片的尺寸
`cfg.WIDTH = 400
cfg.HEIGHT = 400`

更改之后，bbox的位置就不对了
![400_400](https://user-images.githubusercontent.com/43459433/116983465-bb5b7000-acfc-11eb-93bb-cae8fd4b0779.png)

可视化位姿我用了PvNet中的project函数，传入3d_corners，pose和k之后得到2d_corners，再绘制bbox。

def project(xyz, K, RT):
    """
    xyz: [N, 3]
    K: [3, 3]
    RT: [3, 4]
    """
    xyz = np.dot(xyz, RT[:, :3].T) + RT[:, 3:].T
    xyz = np.dot(xyz, K.T)
    xy = xyz[:, :2] / xyz[:, 2:]
    return xy

然后我发现，更改了图片的输出大小（改成400x400）后，pose没有发生任何改变，这也导致调用project函数返回的2d_corners没有变。

比如下面是某次返回的2d_corners，在640x480的图片中的bbox就是正确的，但是在400x400的图片中bbox就发生了偏移，就像上面的那个图片一样。
![corners](https://user-images.githubusercontent.com/43459433/116983974-4f2d3c00-acfd-11eb-8bbb-f0f0ab858d18.jpg)
请问怎么解决这个问题呢？希望能得到作者的回复，谢谢！

**Comment by pengsida** [comment]
你好，

抱歉回复比较晚。
这个代码不支持修改图片尺寸，因为这样需要同时修改相机内参。这个代码不支持自定义blender的相机内参。
建议使用这个代码做渲染：https://github.com/DLR-RM/BlenderProc

**Comment by lqz123** [comment]
谢谢作者
