### ISSUE TITLE
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f068ffb3000  Aborted (core dumped)

### ISSUE THREAD

**Issue by lamhungphu** [zju3dv/pvnet-rendering#62]

**Comment by lamhungphu** [comment]
I complied this line _!python3.5  /content/pvnet-rendering/run.py --type rendering (on colab) and got this issue. Can anyone kindly please help me?

**Comment by lamhungphu** [comment]
![ScreenShot_20210521160258](https://user-images.githubusercontent.com/57521804/119112211-10fa8100-ba4e-11eb-8d90-8633718fe384.png)

**Comment by dizcza** [comment]
@undead4569 could you describe the fix?
