### ISSUE TITLE
found bundled python: /content/blender-2.79a-linux-glibc219-x86_64/2.79/python Read blend: /content/pvnet-rendering/data/blank.blend

### ISSUE THREAD

**Issue by lamhungphu** [zju3dv/pvnet-rendering#63]
Can anyone help me with this? When I run this command _python run.py --type rendering_ , I got this error:
![image](https://user-images.githubusercontent.com/57521804/119167868-808e6180-ba8a-11eb-81ed-d836a98f6e8a.png)

**Comment by liuicheng123** [comment]
> Can anyone help me with this? When I run this command _python run.py --type rendering_ , I got this error: ![image](https://user-images.githubusercontent.com/57521804/119167868-808e6180-ba8a-11eb-81ed-d836a98f6e8a.png)
Hi. how do you solve the problem? i encounter the same question now.
