### ISSUE TITLE
请问出现这个情况怎么办

### ISSUE THREAD

**Issue by liuicheng123** [zju3dv/pvnet-rendering#65]
![微信图片_20211025181219](https://user-images.githubusercontent.com/36021763/138677690-5b77f243-b131-4e0a-984c-0bc735066ccb.jpg)
问什么这个直接就blender quit了，3秒结束？
同时提问这个rendering的10k张图片有没有直接渲染好的提供呀？ 自己render 过程中bug不断。

**Comment by pengsida** [comment]
我们没有提供渲染好的图片。
可以打断点看看blender到哪一步的时候quit。
这个网站有提供渲染好的图片：https://bop.felk.cvut.cz/datasets/

**Comment by FabienCode** [comment]
@liuicheng123 我也遇到这种情况了 请问你解决这个问题了吗
