### ISSUE TITLE
:question: Generate linemod dataset from custom 3D model

### ISSUE THREAD

**Issue by DRM-Free** [zju3dv/pvnet-rendering#67]
I have my own 3D model that I want to use to generate a linemod-like dataset. Can I do it with pvnet-rendering?

**Comment by madhumilan** [comment]
Hi,

Thanks for opening this issue. Even I have a similar question, I need to generate a dataset similar to LineMOD using 3D model of custom objects. @pengsida Can you please let us know if this is possible with pvnet-rendering?

Thanks.

**Comment by pengsida** [comment]
Yes. But I recommend to render the 3D model with the code: https://github.com/DLR-RM/BlenderProc

**Comment by DRM-Free** [comment]
Thank you for pointing out this repo. I'm trying to replicate [this](https://github.com/THU-DA-6D-Pose-Group/GDR-Net). They both use your dataset and pbr dataset from blenderproc. My question is should I just use blenderproc or would there be any benefit in using both pbr and non-pbr rendering? Also, if it turns out that I need both, what would be the procedure for generating my data with your code?

**Comment by pengsida** [comment]
I am not sure if there is any benefit in using both pbr and non-pbr rendering. You could revise the released code to render your 3D model.
