### ISSUE TITLE
Generate for custom object

### ISSUE THREAD

**Issue by RoyAmoyal** [zju3dv/pvnet-rendering#68]
Hey, I generated my custom dataset using https://github.com/F2Wang/ObjectDatasetTools just like clean-pvnet mentioned.

In run_rendering function I will change:
   renderer=Renderer('cat')
to 
   renderer=Renderer('milk')

In  Rendering I change 
 intrinsic_matrix = {
        'linemod': np.array([[572.4114, 0., 325.2611],
                              [0., 573.57043, 242.04899],
                              [0., 0., 1.]]),

to the intrinsic matrix of my camera. 

*Do I have to change the blender_matrix?

what else do I have to change in your code to render images for my own object dataset? 

thanks!

**Comment by pengsida** [comment]
You could use this project for rendering: https://github.com/DLR-RM/BlenderProc

**Comment by bjutlss** [comment]
Have you solved it? I had a similar problem @RoyAmoyal
