### ISSUE TITLE
pvnet error

### ISSUE THREAD

**Issue by lovesuiyue** [zju3dv/pvnet-rendering#74]
(pvnet) zyb@zyb-pc:~/Desktop/pvnet-rendering-master$ ln -s /home/zyb/Desktop/pvnet-rendering-master/data/datasets/LINEMOD ./data/LINEMOD
ln: 无法创建符号链接'./data/LINEMOD/LINEMOD': 文件已存在
(pvnet) zyb@zyb-pc:~/Desktop/pvnet-rendering-master$ ln -s /home/zyb/Desktop/pvnet-rendering-master/data/datasets/SUN2012pascalformat ./data/SUN
ln: 无法创建符号链接'./data/SUN/SUN2012pascalformat': 文件已存在
(pvnet) zyb@zyb-pc:~/Desktop/pvnet-rendering-master$ ln -s /home/zyb/Desktop/pvnet-rendering-master/data/datasets/LINEMOD_ORIG ./data/LINEMOD_ORIG
ln: 无法创建符号链接'./data/LINEMOD_ORIG/LINEMOD_ORIG': 文件已存在

**Comment by lovesuiyue** [comment]
parser.add_argument('--bg_imgs', type=str, default='/home/zyb/Desktop/pvnet-rendering-master/data/blender_poses/bg_imgs.npy',help='Names of background images stored in a .npy file.')
l try not success

**Comment by pengsida** [comment]
The path is not set correctly.
