### ISSUE TITLE
How to get mask

### ISSUE THREAD

**Issue by Benjobs1** [zju3dv/pvnet-rendering#75]

**Comment by Benjobs1** [comment]
请问一下可以获取render数据的mask吗？

**Comment by pengsida** [comment]
可以通过渲染的depth获得物体的mask。

**Comment by Benjobs1** [comment]
> 可以通过渲染的depth获得物体的mask。

谢谢您提供的工具，我rending得到的depth每一个像素值都是0，我不知道是哪里出错了，jpg图片是正常的

**Comment by Benjobs1** [comment]
我是将linemod数据集中duck中的ply文件替换为我自己模型的ply文件，再进行渲染的，您好，请问这样得到的.pkl位姿是正确的吗？
