### ISSUE TITLE
如何render自己的数据集?

### ISSUE THREAD

**Issue by bjutlss** [zju3dv/pvnet-rendering#77]
@pengsida 您好，在使用该仓库时，我成功对LINEMOD数据集进行了render和fuse，但是我想请教一下如何render自己的数据集？
1.   我成功制作了自己的LINEMOD格式的数据集，其中包括了depth、rgb、mask、mesh.ply、以及图片的位姿，但是render自己的数据集时会报错LINEMOD_ORIG/object/OLD_mesh.ply、transform.dat等文件的缺失，我想请问一下如何修改代码来render自己的数据集，或者是如何生成LINEMOD_ORIG中对应的文件？谢谢您的回答。

**Comment by pengsida** [comment]
你好。因为这个代码已经是几年前写的，我已经不太熟悉。推荐使用这个代码库：https://github.com/DLR-RM/BlenderProc
