### ISSUE TITLE
ImportError: No module named 'transforms3d'

### ISSUE THREAD

**Issue by doublechenchen** [zju3dv/pvnet-rendering#8]
how to solve this problem?

(pytorch041) cc@cc:~/pvnet-rendering$ python 
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from transforms3d.euler import euler2mat
>>> 
[1]+  Stopped                 python
(pytorch041) cc@cc:~/pvnet-rendering$ python run.py --type rendering
found bundled python: /home/cc/Downloads/blender-2.79b-linux-glibc219-x86_64/2.79/python
Read blend: /home/cc/pvnet-rendering/data/blank.blend
Traceback (most recent call last):
  File "/home/cc/pvnet-rendering/blender/render_backend.py", line 7, in <module>
    from transforms3d.euler import euler2mat
ImportError: No module named 'transforms3d'

Blender quit

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet-rendering/issues/3

**Comment by Jdeepa** [comment]
pip install transforms3d
