### ISSUE TITLE
content of bg_imgs.npy

### ISSUE THREAD

**Issue by monajalal** [zju3dv/pvnet-rendering#82]
Can you please cat the content of bg_imgs.npy file? Mine is empty.

https://github.com/zju3dv/pvnet-rendering/issues/20#issuecomment-529264859

**Comment by mmkolbe** [comment]
in my case, I ran the run.py before setting the path for the data/SUN properly.
Then the bg_imgs.npy was generated empty.
After fixing the path, I removed and ran run.py again, then the bg_imgs.npy was generated correctly.
