### ISSUE TITLE
Import and export ply file with the texture

### ISSUE THREAD

**Issue by DHNicoles** [zju3dv/pvnet-rendering#9]
Hi. In the original ply I had a texture and some texture coordinates. It seems that information about **texture and textcoords** is completely ignored during import. How can I import all data from ply file including texture info? Is there a custom script for this task or I have to write it myself? I cannot believe that nobody faced the same problem.

**Comment by pengsida** [comment]
What do you want to do by importing these information?
Use what to import the ply file, blender or python?

**Comment by DHNicoles** [comment]
Because my ply file contains additional textures, their format is jpeg. I want to import it in python, after some trial, but it didn't work.
Thank you for your reply！

**Comment by pengsida** [comment]
OpenGL might work.
